import * as s3 from "aws-cdk-lib/aws-s3";
import * as iam from "aws-cdk-lib/aws-iam";
import * as api_gw from "aws-cdk-lib/aws-apigateway";
import { Construct,  } from 'constructs';


export interface IngestProps {
    /** props needed to work **/
    bucketname: string,
  }

export class IngestStack extends Construct {

  constructor(scope: Construct, id: string, props: IngestProps) {
    super(scope, id);

    // Bucket donde se almacenarán los archivos 
    const dataBucket = new s3.Bucket(this, "ingestion-bucket-id", {
        bucketName: props.bucketname,
        eventBridgeEnabled: true,
    });
    // Rol de IAM a asignar al Api Gateway
    const apiGWRole = new iam.Role(this, "api-gateway-role-id", {
      assumedBy: new iam.ServicePrincipal("apigateway.amazonaws.com"),
      roleName: "API-Gateway-S3-Integration-Role",
      description: "Rol de IAM para que un AP GW pueda guardar archivos en S3",
  });

  // Añademos un Policy al rol de IAM
  apiGWRole.addToPolicy(
      new iam.PolicyStatement({
          resources: [dataBucket.bucketArn + "/*"],
          actions: ["s3:PutObject"],
      })
  );

  // API Gateway para ingestar los archivos
  const apiGateway = new api_gw.RestApi(this, "data-api-id", {
      restApiName: "Files receiver",
      description: "Recibe archivos para poder almacenarlos en S3.",
      binaryMediaTypes: ["*/*"],
      endpointTypes: [api_gw.EndpointType.REGIONAL],
      defaultMethodOptions: {
        apiKeyRequired: true
      }
    });

    // Añadimos un usage plan para la API
  const basicUsagePlan = apiGateway.addUsagePlan('UsagePlan', {
    name: "MyUsagePlan",
    apiStages: [{
      api: apiGateway,
      stage: apiGateway.deploymentStage
    }],
    throttle: {
        burstLimit: 100,
        rateLimit: 200
      },
    quota: {
        limit: 10000,
        period: api_gw.Period.MONTH
      },
    description: "Ingestion API GW usage plan."
  })

  const basicApikey = apiGateway.addApiKey( `MyAPIkey`, {
    //apiKeyName, // this can be autogenerated
    description: `APIKey para asegurar la API de ingesta.`,
  })

  basicUsagePlan.addApiKey(basicApikey);

  // Añadir una integración para el API Gateway con S3
  const s3Integration = new api_gw.AwsIntegration({
  service: "s3",
  integrationHttpMethod: "PUT",
  path: `${dataBucket.bucketName}/ingestion/{key}`,
  options: {
      credentialsRole: apiGWRole,
      integrationResponses: [
        {
          statusCode: "200",
          responseParameters: {
            "method.response.header.Content-Type": "integration.response.header.Content-Type",
          },
        },
      ],
      requestParameters: {
      "integration.request.path.key": "method.request.path.key",
      },
  },
  });


  //Añadir los recursos al API Gateway y un método ligado a la integración de S3
  apiGateway.root
  .addResource("upload")
  .addResource("{key}")
  .addMethod("PUT", s3Integration, {
    methodResponses: [
      {
        statusCode: "200",
        responseParameters: {
          "method.response.header.Content-Type": true,
        },
      },
    ],
    requestParameters: {
      "method.request.path.key": true,
    },
    
  }
  );

  }
}

